language: python
os: linux

python:
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - pip install poetry

install:
  - poetry install -v -E cli
  - pip install tox-travis

script:
  - tox

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build

deploy:
  provider: script
  script: poetry publish
  cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"

env:
  global:
    - secure: aMOeCTSNpjXRDlH9FAckTHfN6sImPEMVKUArl74TBsn1xXB1AgP8RoVRJWNOLGS1WaOHV3SI2re79CVQ1Yo8cvN5jcUUP9tEzXdnN7IE4+FymwYSaB96reQPNmlwwH7lY3dfI4u2yuXB+ggVaz/UmEo13Dij1m3HKmj9PWBymL5y1QLsNidwJxli6vpa/xNV2BTUnHqIeFILarExQ8yUA6Xa/8AImzky2bh2Iprhty+J49a0eucBcMlK4e7QiEuJjTIrgtmRnXtbOgQ9Po6tKnkjqHlId7SzVz7jnkLQUUXoj7qdZij4Tli1ZDgR1wpEIUUnTFl5lryQzhJpOwKjZWxiT7fxEX4t5wUbtzAY+7LUMR2CeSugxX4AU7BZyz9cDLUJbETaZuvWNKWuK19x8L66W/Rm/hOum9qHbiV4jUTLKykN+2iRUh15rdQSBOy/ltrYbVswYFN+SEjGLGJ3QLkhWUuJlw/Z4JWALTgMODu07TQW/PBNoh0JTu5T9f0G8+8C7/tPqAUecweTb/ZIeRXziuHhcLQwAW9zNUmBShn8zXxbFLTC2tC4KBwkxGrUn5O9V8E9HoOTagvUpfuimtMMXcbhn/pCEujM1HOoFwwviwl19v1c3Ry5bETbC0R773Wk3L3NT9tipDVY7vMEhBWHIvTHVg8ge2jnnkazvss=
    - secure: LMq+/0R2qCrKQDLdAi3SQdQzvFViDfiuT1ePgNTGgNZAVzMqJhxMeouuhrpEbqAcoe0j0tGZQMskAYDoFXxpb4yaZldTmwu5r0fmZzQKh0CIc3fCsYsRuQhBk11Re+vihSbhK0DllhaQuv4Kv7c6hoNlIZWN0CSKXoFI/KVMSsEAJ5Q2XvgKXRQoFEzmWodZZgyPYpqhfDIiLq+MC1EhMLTKynVNTqezVezcAfpfwMCf0shhPzJTRolBY9KOduGHxHq/A/ztzokzlRgZHfYRyp4vwjTkC56EuqFjsbvOfLFlj0HLIm/sKtu8tG2U+vTl0HC9DqquaPMu8eXuPhn3avasThGcgLztC6xCbXlSqcYO3SF+pGoYnKexM/gLvONauNM8F3pd17ToGRebtm7xQH8853EVgt6eIMt90lHu9SYIc2+PHV4b2ZniWZ3VM2ryO86XO50M3h4nRJ0PjeEnNL3qqCgRaoDDOpX4haUhZn3wFaQPeYU3aK0UfMf5Lg6EsP7fNOo1YxUDlzgvhmuq+WG1Ws7z7ETQU4oEMSUQ6yLd1pdLx87Nqm/s5n93p8r3h4K36TFZotO301QKZokTA8yhoNVlOkJD0LMQMm6wP3zFPXagZGlD1jdkA34fjxSlyxFeURs8hyMwbd0c/RENqAMJLQmGUa27UxW2UYrIen8=
